"""add workspace_anthropic_keys

Revision ID: 416554badf76
Revises: 715ac1917b74
Create Date: 2026-05-21 08:43:37.366103

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '416554badf76'
down_revision: Union[str, None] = '715ac1917b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_anthropic_keys',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('key_nonce', sa.LargeBinary(length=12), nullable=False),
    sa.Column('key_ct', sa.LargeBinary(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_anthropic_keys')
    # ### end Alembic commands ###
