"""add agents and slack_threads

Revision ID: 715ac1917b74
Revises: f34663084e56
Create Date: 2026-05-21 08:27:46.350758

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '715ac1917b74'
down_revision: Union[str, None] = 'f34663084e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('anthropic_agent_id', sa.String(length=64), nullable=False),
    sa.Column('environment_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_workspace_default_active', 'agents', ['workspace_id'], unique=True, postgresql_where=sa.text('is_default AND archived_at IS NULL'))
    op.create_index('ix_agents_workspace_slug_active', 'agents', ['workspace_id', 'slug'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_table('slack_threads',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('thread_ts', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('last_session_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'channel_id', 'thread_ts')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_threads')
    op.drop_index('ix_agents_workspace_slug_active', table_name='agents', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index('ix_agents_workspace_default_active', table_name='agents', postgresql_where=sa.text('is_default AND archived_at IS NULL'))
    op.drop_table('agents')
    # ### end Alembic commands ###
