"""add workspace_slack_installs

Revision ID: f34663084e56
Revises: 4358aa95491b
Create Date: 2026-05-21 07:48:35.939666

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f34663084e56'
down_revision: Union[str, None] = '4358aa95491b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_slack_installs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('slack_team_id', sa.String(length=32), nullable=False),
    sa.Column('slack_team_name', sa.String(length=255), nullable=False),
    sa.Column('bot_user_id', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.String(length=32), nullable=False),
    sa.Column('enterprise_id', sa.String(length=32), nullable=True),
    sa.Column('enterprise_name', sa.String(length=255), nullable=True),
    sa.Column('bot_token_nonce', sa.LargeBinary(length=12), nullable=False),
    sa.Column('bot_token_ct', sa.LargeBinary(), nullable=False),
    sa.Column('scopes_granted', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('installed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['installed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_slack_installs_team_active', 'workspace_slack_installs', ['slack_team_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_workspace_slack_installs_workspace_active', 'workspace_slack_installs', ['workspace_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_slack_installs_workspace_active', table_name='workspace_slack_installs', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_workspace_slack_installs_team_active', table_name='workspace_slack_installs', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('workspace_slack_installs')
    # ### end Alembic commands ###
